src/akwarium-backend/aquarium/urls.py
from django.urls import path, include
from rest_framework import routers

from aquarium.api.views import UpdateSetpoints, UpdateLightHours
from aquarium.api.viewsets import PointValueViewSet, MeasuringDeviceViewSet, ExecutiveDeviceViewSet, \
    DeviceParameterMeasuredViewSet, SetpointViewSet
from aquarium.views import index, settings

app_name = 'aquarium'

router = routers.DefaultRouter()
router.register(r'point_value', PointValueViewSet, basename='point_value')
router.register(r'measuring_device', MeasuringDeviceViewSet, basename='measuring_device')
router.register(r'executive_device', ExecutiveDeviceViewSet, basename='executive_device')
router.register(r'device_parameter', DeviceParameterMeasuredViewSet, basename='device_parameter')
router.register(r'setpoint', SetpointViewSet, basename='setpoint')

urlpatterns = [
    path('api/', include(router.urls)),
    path('api/update_setpoints/', UpdateSetpoints.as_view()),
    path('api/light_hours/', UpdateLightHours.as_view()),
    path('', index, name='index'),
    path('settings/', settings, name='settings')

]

src/akwarium-backend/server/urls.py
from django.contrib import admin
from django.urls import re_path, include
from aquarium.tasks import startup

urlpatterns = [
    re_path(r'', include('aquarium.urls', namespace='aquarium')),
    re_path(r'^admin/', admin.site.urls),
]

# https://stackoverflow.com/a/6792076
startup.delay()

src/akwarium-backend/aquarium/models.py
from django.contrib import admin
from django.db import models


class Parameter(models.Model):
    name = models.CharField('Nazwa jednostki', max_length=32, unique=True)
    processed_name = models.CharField('Angielska nazwa', max_length=32, unique=True)
    unit = models.CharField('Jednostka', max_length=5)

    def __str__(self):
        return f"{self.name} - {self.unit}"

    class Meta:
        verbose_name = "Parametr"
        verbose_name_plural = "Parametry"
        app_label = "aquarium"


class MeasuringDevice(models.Model):
    name = models.CharField('Nazwa urządzenia', max_length=64, unique=True)
    address = models.CharField('Pin lub adres', max_length=4, unique=True)
    is_i2c = models.BooleanField("I2C", default=False)
    is_out = models.BooleanField('Wyjście', default=1)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Urządzenie pomiarowe"
        verbose_name_plural = "Urządzenia pomiarowe"
        app_label = "aquarium"
        ordering = ("address",)


class ExecutiveDevice(models.Model):
    name = models.CharField('Nazwa urządzenia', max_length=64, unique=True)
    pin = models.PositiveSmallIntegerField('Pin', unique=True)
    is_out = models.BooleanField('Wyjście', default=1)
    state = models.BooleanField('Stan', default=1)
    channel = models.FloatField('Kanał', null=True, blank=True)
    cron = models.BooleanField('Przełączanie przez cron', default=False)

    @admin.display(description="Kanał")
    def parsed_channel(self):
        return f"{self.channel:g}"

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Urządzenie wykonawcze"
        verbose_name_plural = "Urządzenia wykonawcze"
        app_label = "aquarium"
        ordering = ("pin",)


class Setpoint(models.Model):
    parameter = models.ForeignKey(Parameter, on_delete=models.CASCADE, verbose_name="Parametr")
    value = models.FloatField('Zadana wartość')

    def __str__(self):
        return f"{self.parameter.name} - {self.value}{self.parameter.unit}"

    class Meta:
        verbose_name = "Zadana wartość"
        verbose_name_plural = "Zadane wartości"
        app_label = "aquarium"


class TaskSequence(models.Model):
    name = models.CharField('Nazwa sekwencji', max_length=128)
    is_active = models.BooleanField('Czy aktywna', default=False)
    hysteresis = models.FloatField('Histereza', default=2)
    setpoint = models.ForeignKey(Setpoint, on_delete=models.CASCADE, null=True, blank=True,
                                 verbose_name="Powiązana wartość zadana")
    comparator = models.CharField("Komparator", max_length=4)
    startup_value = models.BooleanField('Stan przy uruchomieniu', default=False)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        verbose_name = "Sekwencja układu"
        verbose_name_plural = "Sekwencje układów"
        app_label = "aquarium"


class TaskPrecedingSequence(models.Model):
    sequence_to_check = models.ForeignKey(TaskSequence, on_delete=models.CASCADE, verbose_name="Sekwencja sprawdzana",
                                          related_name="task_sequence_checked")
    executed_sequence = models.ForeignKey(TaskSequence, on_delete=models.CASCADE, verbose_name="Sekwencja wykonywana",
                                          related_name="task_sequence_executed")

    def __str__(self):
        return f"Wykonaj {self.executed_sequence.name} jeśli {self.sequence_to_check.name} jest aktywna"

    class Meta:
        verbose_name = "Warunek wykonywania sekwencji"
        verbose_name_plural = "Warunki wykonywania sekwencji"
        app_label = "aquarium"


class TaskSequenceStep(models.Model):
    sequence = models.ForeignKey(TaskSequence, on_delete=models.CASCADE, verbose_name="Sekwencja")
    device = models.ForeignKey(ExecutiveDevice, on_delete=models.CASCADE, verbose_name="Urządzenie wykonawcze")
    order = models.PositiveSmallIntegerField("Kolejność wykonywania", default=1)
    delay = models.PositiveSmallIntegerField("Opóźnienie po wykonaniu", default=1000)
    output_value = models.BooleanField("Stan", default=True)

    def __str__(self):
        return f"{self.sequence} - {self.device.name}"

    class Meta:
        verbose_name = "Powiązanie urządzenia w sekwencji"
        verbose_name_plural = "Powiązania urządzeń w sekwencjach"
        app_label = "aquarium"


class DeviceParameterMeasured(models.Model):
    device = models.ForeignKey(MeasuringDevice, on_delete=models.CASCADE, verbose_name='Urządzenie')
    parameter = models.ForeignKey(Parameter, on_delete=models.CASCADE, verbose_name='Parametr')

    def __str__(self):
        return f"{self.device} - {self.parameter.name}"

    class Meta:
        verbose_name = "Wartość zbierana przez urządzenie"
        verbose_name_plural = "Wartości zbierane przez urządzenia"
        app_label = "aquarium"


class PointValue(models.Model):
    device_parameter = models.ForeignKey(DeviceParameterMeasured, on_delete=models.CASCADE,
                                         verbose_name='Urządzenie i parametr')
    value = models.FloatField('Wartość pomiaru')
    timestamp = models.DateTimeField('Data pomiaru', auto_now_add=True)

    @admin.display(description="Wartość")
    def custom_value(self):
        return f"{self.value}{self.device_parameter.parameter.unit}"

    @admin.display(description="Urządzenie")
    def device_name(self):
        return self.device_parameter.device.name

    @admin.display(description="Parametr")
    def parameter_name(self):
        return self.device_parameter.parameter.name

    def __str__(self):
        return f"[{self.timestamp}] {self.device_parameter.device.name} - {self.value}"

    class Meta:
        verbose_name = "Pomiar"
        verbose_name_plural = "Pomiary"
        app_label = "aquarium"

src/akwarium-backend/aquarium/api/views.py
from django.http import HttpResponse, JsonResponse
from rest_framework import permissions
from rest_framework.views import APIView
from aquarium.models import Setpoint
from django_celery_beat.models import PeriodicTask


class UpdateSetpoints(APIView):
    permission_classes = [permissions.AllowAny]

    @staticmethod
    def post(request):
        data = request.data['data']

        for setpoint in data:
            sp_obj = Setpoint.objects.get(id=setpoint['id'])
            sp_obj.value = float(setpoint['value'])
            sp_obj.save()

        return HttpResponse(status=200)


class UpdateLightHours(APIView):
    permission_classes = [permissions.AllowAny]

    @staticmethod
    def get(request):
        light_on = PeriodicTask.objects.get(task="aquarium.tasks.switch_light", args="[0]")
        light_off = PeriodicTask.objects.get(task="aquarium.tasks.switch_light", args="[1]")

        time_on = f"{light_on.crontab.hour}:{light_on.crontab.minute}"
        time_off = f"{light_off.crontab.hour}:{light_off.crontab.minute}"

        return JsonResponse({"on": time_on, "off": time_off})

    @staticmethod
    def post(request):
        data = request.data['data']

        light_on = PeriodicTask.objects.get(task="aquarium.tasks.switch_light", args="[0]")
        light_off = PeriodicTask.objects.get(task="aquarium.tasks.switch_light", args="[1]")

        cron_on = light_on.crontab
        cron_off = light_off.crontab

        cron_on.hour, cron_on.minute = data['on'].split(':')
        cron_off.hour, cron_off.minute = data['off'].split(':')

        cron_on.save()
        cron_off.save()

        return HttpResponse(status=200)

src/akwarium-backend/aquarium/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')


def settings(request):
    return render(request, 'settings.html')

src/akwarium-backend/aquarium/templates/base.html
{% load static %}

{% url 'aquarium:index' as index %}
{% url 'aquarium:settings' as settings %}

<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
    {#        <link rel="stylesheet" href="{% static 'styles/styles.css' %}">#}
    <script src="{% static 'js/tailwind.js' %}"></script>
    <script src="{% static 'js/axios.js' %}"></script>
    <script src="{% static 'js/endpoints.js' %}"></script>
    <script src="{% static 'js/functions.js' %}"></script>
    {#        <link rel="icon" href="{% static '/favicon.png' %}">#}
    <title>Akwarium</title>
    {% block head_extras %}
    {% endblock %}
</head>

<body class="bg-gray-100 font-sans leading-normal tracking-normal">
<nav id="header" class="bg-white fixed w-full z-10 top-0 shadow">
    <div class="w-full container mx-auto flex flex-wrap items-center mt-0 pt-3 md:pb-0">
        <div class="w-1/2 pl-2 md:pl-0 xl:mb-1 mb-2">
            <a class="text-gray-900 text-base xl:text-xl no-underline hover:no-underline font-bold"
               href="{% url 'aquarium:index' %}">
                <i class="fas fa-sun text-pink-600 pr-3"></i>Akwarium
            </a>
        </div>
        <div class="w-1/2 pr-0"></div>
        <div class="w-full flex-grow lg:flex lg:items-center lg:w-auto hidden lg:block mt-2 lg:mt-0 bg-white z-20"
             id="nav-content">
            <ul class="list-reset lg:flex flex-1 items-center px-4 md:px-0">
                <li class="px-4 m-2 md:my-0 border-gray-300 hover:border-gray-600 border-b-2 {% if request.path == index %} border-gray-700 text-gray-900 {% endif %}">
                    <a href="{% url 'aquarium:index' %}"
                       class="block py-1 md:py-3 align-middle no-underline hover:text-gray-900"><span
                            class="pb-1 md:pb-0 text-sm">Pomiary</span>
                    </a>
                </li>
                <li class="px-4 m-2 md:my-0 border-gray-300 hover:border-gray-600 border-b-2 {% if request.path == settings %} border-gray-700 text-gray-900 {% endif %}">
                    <a href="{% url 'aquarium:settings' %}"
                       class="block py-1 md:py-3 align-middle text-gray-500 no-underline hover:text-gray-900"><span
                            class="pb-1 md:pb-0 text-sm">Ustawienia</span>
                    </a>
                </li>
                <li class="px-4 m-2 md:my-0 border-gray-300 hover:border-gray-600 border-b-2">
                    <a href="{% url 'admin:index' %}"
                       class="block py-1 md:py-3 align-middle text-gray-500 no-underline hover:text-gray-900"><span
                            class="pb-1 md:pb-0 text-sm">Zarządzanie</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<main class="container w-full mx-auto pt-20">
    <div class="w-full px-4 md:px-0 md:mt-8 mb-16 text-gray-800 leading-normal">
        {% block content %}
        {% endblock %}
    </div>
</main>

</body>
{% block script %}
{% endblock %}
</html>

src/akwarium-backend/aquarium/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block head_extras %}
    <script src="{% static 'js/chart.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="flex flex-wrap">
        <!-- górne karty -->
        <div class="w-full md:w-1/2 xl:w-1/2 p-3">
            <div class="bg-white border rounded shadow p-2">
                <div class="flex flex-row items-center">
                    <div class="flex-shrink pr-4">
                        <div class="rounded p-3 bg-gray-100">
                            <svg style="width:24px;height:24px" viewBox="0 0 24 24">
                                <path fill="currentColor"
                                      d="M19 8C20.11 8 21 8.9 21 10V16.76C21.61 17.31 22 18.11 22 19C22 20.66 20.66 22 19 22C17.34 22 16 20.66 16 19C16 18.11 16.39 17.31 17 16.76V10C17 8.9 17.9 8 19 8M19 9C18.45 9 18 9.45 18 10V11H20V10C20 9.45 19.55 9 19 9M12 5.69L7 10.19V18H14.1L14 19L14.1 20H5V12H2L12 3L16.4 6.96C15.89 7.4 15.5 7.97 15.25 8.61L12 5.69Z"></path>
                            </svg>
                        </div>
                    </div>
                    <div class="flex-1 text-right md:text-center">
                        <h5 class="font-bold uppercase text-gray-500">Zbierane metryki</h5>
                        <h3 class="font-bold text-3xl flex justify-center items-center" id="measurementDevicesNumber">
                            <svg style="width:24px;height:24px" viewBox="0 0 24 24" class="animate-spin my-2">
                                <path fill="currentColor"
                                      d="M2 12C2 16.97 6.03 21 11 21C13.39 21 15.68 20.06 17.4 18.4L15.9 16.9C14.63 18.25 12.86 19 11 19C4.76 19 1.64 11.46 6.05 7.05C10.46 2.64 18 5.77 18 12H15L19 16H19.1L23 12H20C20 7.03 15.97 3 11 3C6.03 3 2 7.03 2 12Z"></path>
                            </svg>
                        </h3>
                    </div>
                </div>
            </div>
        </div>
        <div class="w-full md:w-1/2 xl:w-1/3 p-3">
            <div class="bg-white border rounded shadow p-2">
                <div class="flex flex-row items-center">
                    <div class="flex-shrink pr-4">
                        <div class="rounded p-3 bg-gray-100">
                            <svg style="width:24px;height:24px" viewBox="0 0 24 24">
                                <path fill="currentColor"
                                      d="M10,9A1,1 0 0,1 11,8A1,1 0 0,1 12,9V13.47L13.21,13.6L18.15,15.79C18.68,16.03 19,16.56 19,17.14V21.5C18.97,22.32 18.32,22.97 17.5,23H11C10.62,23 10.26,22.85 10,22.57L5.1,18.37L5.84,17.6C6.03,17.39 6.3,17.28 6.58,17.28H6.8L10,19V9M11,5A4,4 0 0,1 15,9C15,10.5 14.2,11.77 13,12.46V11.24C13.61,10.69 14,9.89 14,9A3,3 0 0,0 11,6A3,3 0 0,0 8,9C8,9.89 8.39,10.69 9,11.24V12.46C7.8,11.77 7,10.5 7,9A4,4 0 0,1 11,5M11,3A6,6 0 0,1 17,9C17,10.7 16.29,12.23 15.16,13.33L14.16,12.88C15.28,11.96 16,10.56 16,9A5,5 0 0,0 11,4A5,5 0 0,0 6,9C6,11.05 7.23,12.81 9,13.58V14.66C6.67,13.83 5,11.61 5,9A6,6 0 0,1 11,3Z"></path>
                            </svg>
                        </div>
                    </div>
                    <div class="flex-1 text-right md:text-center">
                        <h5 class="font-bold uppercase text-gray-500">Urządzenia wykonawcze</h5>
                        <h3 class="font-bold text-3xl flex justify-center items-center" id="executiveDevicesNumber">
                            <svg style="width:24px;height:24px" viewBox="0 0 24 24" class="animate-spin my-2">
                                <path fill="currentColor"
                                      d="M2 12C2 16.97 6.03 21 11 21C13.39 21 15.68 20.06 17.4 18.4L15.9 16.9C14.63 18.25 12.86 19 11 19C4.76 19 1.64 11.46 6.05 7.05C10.46 2.64 18 5.77 18 12H15L19 16H19.1L23 12H20C20 7.03 15.97 3 11 3C6.03 3 2 7.03 2 12Z"></path>
                            </svg>
                        </h3>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Divider -->
    <hr class="border-b-1 border-gray-400 my-8 mx-4">

    <!-- wykresy -->
    <div class="flex flex-row flex-wrap flex-grow mt-2" id="graphsFlexBox">
    </div>


{% endblock %}

{% block script %}
    <script>
        (async () => {
            const mdBlock = document.getElementById('measurementDevicesNumber')
            const metrics  = await getMetricsCounter()
            mdBlock.innerText = metrics.length

            await displayExecutiveDevicesCounter()
            const graphsList = printGraphs(metrics);

            const chartObjects = []

            for (const graph of graphsList) {
                const newGraph = await createGraph(graph)
                chartObjects.push(newGraph)
            }

            setInterval(() => {
                for (const chart of chartObjects) {
                    updateChart(chart)
                }
            }, 30000)

        })();
    </script>
{% endblock %}

src/akwarium-backend/aquarium/templates/settings.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="flex flex-wrap">
        <div class="w-full p-3 relative overflow-x-auto">
            <table class="w-full bg-white border rounded shadow">
                <thead class="text-gray-700 uppercase bg-gray-50">
                <tr>
                    <th scope="col" class="px-6 py-3">Nazwa wartości</th>
                    <th scope="col" class="px-6 py-3">Wartość zadana</th>
                    <th scope="col" class="px-6 py-3">Nowa wartość</th>
                </tr>
                </thead>
                <tbody id="data">
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="2"></td>
                    <th scope="row" class="px-6 py-3">
                        <input type="button" id="sendButton" value="Prześlij" class="hover:cursor-pointer
                        bg-gray-100 py-2 px-6 rounded hover:bg-gray-700 hover:text-white transition duration-200"
                        >
                    </th>
                </tr>
                </tfoot>
            </table>
        </div>

        <hr class="border-b-1 border-gray-400 my-8 mx-4"/>

        <div class="w-full p-3 relative overflow-x-auto">
            <table class="w-full bg-white border rounded shadow">
                <thead class="text-gray-700 uppercase bg-gray-50">
                <tr>
                    <th scope="col" class="px-6 py-3">Zadanie</th>
                    <th scope="col" class="px-6 py-3">Aktualna godzina</th>
                    <th scope="col" class="px-6 py-3">Nowa godzina</th>
                </tr>
                </thead>
                <tbody>
                <tr class="border-b">
                    <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">Włącz oświetlenie</th>
                    <td class="px-6 py-4 text-center" id="turnOnHour"></td>
                    <td class="px-6 py-4">
                        <input type="time"
                               class="shadow appearance-none border rounded
                               w-full py-2 px-3 text-gray-700 leading-tight
                                focus:outline-none focus:shadow-outline" id="formLightOn">
                    </td>
                </tr>
                <tr class="border-b">
                    <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap">Wyłącz oświetlenie
                    </th>
                    <td class="px-6 py-4 text-center" id="turnOffHour"></td>
                    <td class="px-6 py-4">
                        <input type="time"
                               class="shadow appearance-none border rounded
                               w-full py-2 px-3 text-gray-700 leading-tight
                                focus:outline-none focus:shadow-outline" id="formLightOff">
                    </td>
                </tr>
                </tbody>
                <tfoot>
                <tr>
                    <td colspan="2"></td>
                    <th scope="row" class="px-6 py-3">
                        <input type="button" id="sendHoursButton" value="Prześlij" class="hover:cursor-pointer
                        bg-gray-100 py-2 px-6 rounded hover:bg-gray-700 hover:text-white transition duration-200"
                        >
                    </th>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script>
        (async () => {
            const tableBody = document.getElementById('data')
            const setpoints = await getSetpoints()

            const elements = printSetpoints(setpoints);
            elements.forEach(el => {
                tableBody.appendChild(el)
            })

            const sendButton = document.getElementById("sendButton")
            sendButton.addEventListener("click", async () => {
                let valid_values = true
                const inputs = document.querySelectorAll("input[type='number']:not([type='button'])")
                for (const input of inputs) {
                    const errorP = document.getElementById(`error-${input.id}`)
                    errorP.innerText = ""
                    input.classList.remove('border-red-500')
                    if (+input.value <= 0) {
                        input.classList.add('border-red-500')
                        errorP.innerText = "Zadana wartość musi być większa od zera!"
                        valid_values = false
                    }
                }

                if (valid_values) {
                    const postData = []
                    for (const input of inputs) {
                        postData.push({"id": input.id, "value": input.value})
                    }
                    await postSetpoints(postData)
                    location.reload()
                }
            })

            const lightHours = await getLightHours();
            const lightOnDiv = document.getElementById('turnOnHour')
            const lightOffDiv = document.getElementById('turnOffHour')
            lightOnDiv.innerText = `codziennie o ${lightHours.on}`;
            lightOffDiv.innerText = `codziennie o ${lightHours.off}`;

            const inputOn = document.getElementById('formLightOn')
            const inputOff = document.getElementById('formLightOff')
            inputOn.setAttribute('value', lightHours.on)
            inputOff.setAttribute('value', lightHours.off)

            const sendHoursButton = document.getElementById("sendHoursButton")
            sendHoursButton.addEventListener("click", async () => {
                await updateLightHours({"on": inputOn.value, "off": inputOff.value})
                location.reload()
            })
        })()
    </script>
{% endblock %}